blank_issues_enabled: true
contact_links:
  - name: Questions and ideas
    url: https://github.com/smmariquit/eduvisualsph/discussions
    about: For open-ended questions and discussion, use Discussions.
